services:

  backend:
    build: ./backend
    container_name: notes-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - notes-db:/app/database
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: notes-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  notes-db: